path_to_unrealengine="F:/UnrealEngine/Engine/Binaries/Win64/UnrealEditor.exe"
path_to_project="F:/CastleAdventure/CastleAdventure.uproject"
path_to_reports="F:/CastleAdventure/Saved/Reports"
run_tests="Project."
test_exit="Successfully wrote json results file"
